# Generated by Django 2.2.1 on 2019-05-16 18:17

from django.db import migrations, models
import taskWorkers.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(default=taskWorkers.models.create_hash, max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(null=True)),
                ('finished_at', models.DateTimeField(null=True)),
                ('has_error', models.BooleanField(default=False)),
                ('error', models.TextField(null=True)),
                ('progress', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('P', 'Pending'), ('R', 'Running'), ('D', 'Complete')], default='P', max_length=1)),
            ],
        ),
    ]
