# Generated by Django 2.2.1 on 2019-05-21 16:30

from django.db import migrations, models
import taskWorkers.models


class Migration(migrations.Migration):

    dependencies = [
        ('taskWorkers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='hash',
            field=models.CharField(default=taskWorkers.models.create_hash, max_length=25),
        ),
    ]
